export const categoryNames = [
  'pralnice bębnowe czołowe',
  'pralnice bębnowe boczne',
  'pralnice specjalne czołowe',
  'pralnice specjalne boczne',
  'pralnice z barierą higieny',
  'pralnicowirówki wysokoobrotowe',
  'pralnicowirówki szybkoobrotowe',
  'pralnicowirówki normalnoobrotowe',
  'pralnicowirówki normalnoobrotowe o załadunku bocznym',
  'bariery higieny wysokoobrotowe',
  'bariery higieny sztywnomocowane',
  'suszarki bębnowe',
  'suszarki komorowe',
  'suszarki z pompą ciepła',
  'wirówki',
  'prasownice nieckowe',
  'prasownice nieckowe ze składarką',
  'prasownice walcowe',
  'prasownice walcowe ze składarką wzdłużną lub funkcją nawrotu',
  'prasownice walcowe z podawarką i składarką wzdłużną',
  'stoły do prasowania',
  'zestawy pralko - suszarka',
  'zestawy suszarko - suszarka',
  'małe profesionalne pralnicowirówki',
  'małe profesionalne suszarki',
  'pralnicowirówki MOP',
].sort();
export default categoryNames;
