import DEFAULT_PORTRAIT_IMAGE from './default_300_430.webp';
import DEFAULT_LANDSCAPE_IMAGE from './default_600_430.webp';
import DEFAULT_PORTRAIT_THUMBNAIL from './default_64_92.webp';
import DEFAULT_LANDSCAPE_THUMBNAIL from './default_128_92.webp';

export const DEFAULT_IMAGES_PRODUCT_FORM = {
    DEFAULT_PORTRAIT_IMAGE,
    DEFAULT_PORTRAIT_THUMBNAIL,
    DEFAULT_LANDSCAPE_IMAGE,
    DEFAULT_LANDSCAPE_THUMBNAIL,
}
export default DEFAULT_IMAGES_PRODUCT_FORM;
